### ISSUE TITLE
Backport from fork?!

### ISSUE THREAD

**Issue by arlt** [duritong/trocla#60]
Hello @duritong 

There exists a [fork](https://github.com/wintermeyer/trocla-ruby2) wich added sshkey format and made trocla Ruby 2 compatible.

Maybe you should have a look at it and backport some things.

A new release on rubygems.org would be nice, too.

**Comment by duritong** [comment]
How about they provide a MR? And then we can take it from there?

**Comment by arlt** [comment]
As i remember there where MRs for sshkey and for Ruby 2.0 compatibility. They where not accepted by your. So The fork did it...

**Comment by duritong** [comment]
Besides adding the sshkey format (for which there is an MR with failing tests), there are 0 changes for Ruby 2 compatibility in that fork.

Actually, all that was done was removing 1.8.7 from the test suite, which is fair to do, but also what was the reason for the MR to have failing tests. And MRs with failing tests and 0 interactions are very likely to be overlooked / ignored by me.

So I am happy to merge anything that has working tests (even if that means dropping support for some versions). And this is something anybody can propose (instead of "forking" away).

This is a project done in my free time and therefor you cannot expect me to do any work. I already contributed my work to everybody for free and I am happy to interact with others on improving it. But this needs communication and some kind of  engagement. Otherwise things will just stay as they are, as it works for me and thus I have little interest to spend time where there is no benefit for me.

I am closing the issue, though I am not saying not interested in merging these things, but it's clear what needs to happen from here.
